import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import Header from "../src/components/header";
import Profile from "../src/components/profile";
import axios from "axios";
import { useState, useEffect } from "react";

export default function Home() {
  const [perfil, setPerfil] = useState(undefined);
  const [reload, setReload] = useState(0);

  useEffect(() => {
    console.debug("Obteniendo datos del perfil...");

    axios.get("https://api.github.com/users/diegocev").then((response) => {
      if (response.status === 200) {
        setPerfil(response.data);
        console.debug("Positivo carga", response.data);
      }
    });
  }, [reload]);

  let component;

  if (typeof perfil === "undefined") {
    component = <div>No existen datos disponibles.</div>;
  } else {
    component = Profile({ perfil });
  }

  return (
    <div className="container">
      <Head>
        <title>Diego Cevallos Erazo's Profile App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header title="Profile" subtitle="Data from Github's API" type="link" />

        <div className="columns is-multiline">
            {component}
        </div>
      </main>
    </div>
  );
}